name: Repository Setup

on: 
  workflow_dispatch:

jobs:
  ascertain-repo-details:
    name: Extract Repo Info
    runs-on: ubuntu-latest
    outputs:
      repo_title: ${{ steps.repo_info.outputs.repo_title }}
      repo_description: ${{ steps.repo_info.outputs.repo_description }}
      repo_topics: ${{ steps.repo_info.outputs.repo_topics }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Get repository details
        id: repo_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_data=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }})
          echo "repo_title=$(echo $repo_data | jq -r .name)" >> $GITHUB_OUTPUT
          echo "repo_description=$(echo $repo_data | jq -r .description)" >> $GITHUB_OUTPUT
          echo "repo_topics=$(echo $repo_data | jq -r '.topics | join(",")')" >> $GITHUB_OUTPUT

  run-init:
    name: Initial Repository Setup
    needs: ascertain-repo-details
    uses: wwwDayDream-Modding/github-workflows/.github/workflows/init.yml@main
    secrets:
      org_pat: ${{ secrets.ORG_PAT }}
    with: 
      repo_title: ${{ needs.ascertain-repo-details.outputs.repo_title }}
      repo_description: ${{ needs.ascertain-repo-details.outputs.repo_description }}
      repo_topics: ${{ needs.ascertain-repo-details.outputs.repo_topics }}
