name: Repository Initialization

on: 
  workflow_dispatch:

jobs:
  run-init:
    uses: wwwDayDream-Modding/github-workflows/.github/workflows/init.yml@main
    with:
      day_pat: ${{ secrets.DAY_PAT }}
      org_pat: ${{ secrets.ORG_PAT }}
